version: "3.0"
services:
  gateway:
    build:
      context: ./gateway
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -Dspring.cloud.nacos.username=${NACOS_USERNAME} -Dspring.cloud.nacos.password=${NACOS_PASSWORD} -Dspring.cloud.nacos.server-addr=${NACOS_SERVER_ADDR} ${RUN_ARGS}'
    image: gateway
    container_name: gateway
    restart: always
    volumes:
      - /home/roncoo/logs/gateway:/root/logs/gateway
    networks:
      - education
    ports:
      - "7700:7700"
  service-system:
    build:
      context: ./service-system
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -Dspring.cloud.nacos.username=${NACOS_USERNAME} -Dspring.cloud.nacos.password=${NACOS_PASSWORD} -Dspring.cloud.nacos.server-addr=${NACOS_SERVER_ADDR} ${RUN_ARGS}'
    image: service-system
    container_name: system
    restart: always
    volumes:
      - /home/roncoo/logs/system:/root/logs/system
    networks:
      - education
    ports:
      - "7710:7710"
  service-user:
    build:
      context: ./service-user
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -Dspring.cloud.nacos.username=${NACOS_USERNAME} -Dspring.cloud.nacos.password=${NACOS_PASSWORD} -Dspring.cloud.nacos.server-addr=${NACOS_SERVER_ADDR} ${RUN_ARGS}'
    image: service-user
    container_name: user
    restart: always
    volumes:
      - /home/roncoo/logs/user:/root/logs/user
    networks:
      - education
    ports:
      - "7720:7720"
  service-course:
    build:
      context: ./service-course
      args:
        JAVA_OPTS: '-Xmn256M -Xmx256M'
        RUN_ARGS: '-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -Dspring.cloud.nacos.username=${NACOS_USERNAME} -Dspring.cloud.nacos.password=${NACOS_PASSWORD} -Dspring.cloud.nacos.server-addr=${NACOS_SERVER_ADDR} ${RUN_ARGS}'
    image: service-course
    container_name: course
    restart: always
    volumes:
      - /home/roncoo/logs/course:/root/logs/course
    networks:
      - education
    ports:
      - "7730:7730"
networks:
  education:
    driver: bridge
